# Generated by Django 6.0.4 on 2026-05-05 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_migrate_cars_image_to_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carprediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='login.cars')),
            ],
        ),
    ]
